import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE','config.settings')
import django;django.setup()
from company.models import CompanyProfile
from services.models import Service
from projects.models import Project
CompanyProfile.objects.update_or_create(id=1,defaults={'description':'Issabub Nigeria Limited is an Ogun-based general construction and civil engineering firm providing comprehensive project execution for residential, commercial, industrial, and infrastructure clients across Nigeria. Founded on January 28, 2014.','mission':'To deliver high-quality building and civil engineering projects that meet exact standards—delivered on time, within budget, and with uncompromising structural integrity and site safety.','vision':'To remain a dependable, first-choice general contracting firm across Ogun State and Nigeria, recognized for technical capability in structural building and vital infrastructure development.','address':'15, Kajola Estate, Ifelodun Street, Off Gasline, Ijoko Ota, Ogun State','phone':'+2348126843284','email':'issabubngltd@outlook.com'})
services=[('01','Technical Sub-Contracting','technical-sub-contracting','Specialized labor, skilled manpower, and execution support for large-scale industrial and EPC projects.',['Skilled and certified technical personnel','Rapid mobilization and flexible workforce scaling','Safety, quality and schedule discipline']),('02','Mechanical Engineering','mechanical-engineering','Design, analysis, fabrication, installation and commissioning support for mechanical systems and equipment.',['Detailed engineering analysis','Mechanical systems and equipment support','Fabrication and precision manufacturing']),('03','Industrial Maintenance','industrial-maintenance','Scheduled and emergency maintenance for industrial facilities, machinery and critical systems to minimize downtime and extend asset life.',['Preventive maintenance programs','Emergency repair and breakdown support','Maintenance reporting and compliance support']),('04','Building & Construction','building-construction','Complete building construction from groundwork and foundations through structural works, finishing and handover.',['End-to-end project management','Site engineering supervision','Quality, safety and regulatory compliance'])]
for n,t,s,d,b in services: Service.objects.update_or_create(slug=s,defaults={'number':n,'title':t,'description':d,'key_benefits':b,'applications':[],'active':True})
projects=[('Retail Shopping Centre Expansion','commercial','Expansion of an existing shopping centre adding new retail and food-court space, structural works, public plazas and service integration.'),('Office Building Shell & Core','commercial','Construction of a four-storey commercial office building including structural frame, façade, core services and base-build systems.'),('Commercial Warehouse Frame','commercial','Full structural steel framework for a warehouse facility including columns, beams, purlins, girts, bracing and connections.'),('Apartment Fit-Out & Interiors','residential','Complete interior fit-out of a 12-unit residential apartment block including flooring, joinery, ceilings, lighting, plumbing and electrical works.'),('Townhouse Development','residential','Turnkey construction of an eight-unit contemporary townhouse development with courtyards, parking and shared landscaped areas.'),('Family Home Extension & Remodel','residential','Major rear extension and internal remodel involving structural modifications, upgraded bathrooms and integrated finishes.'),('Clinker Transport System Repair','retrofitting','Repair and rehabilitation of a clinker transport system including structural assessment, frame strengthening and conveyor support repair.'),('Office Space Refurbishment','retrofitting','Commercial office renovation including partition systems, ceilings, flooring, lighting, HVAC, electrical and data installations.'),('Industrial Facility Upgrade','retrofitting','Retrofitting of an existing industrial building including structural strengthening, roof replacement, cladding and system upgrades.'),('Sports Arena Roof Truss','structural','Long-span steel roof structure with primary trusses, purlins, bracing, access walkways and connections.'),('Integration of Existing Cement Silo','structural','Integration of an existing cement silo with a new process line through steelwork, platforms, access structures and connections.'),('Industrial Portal Frame Building','structural','Large-span steel portal frame for a manufacturing facility supporting crane runway beams, heavy equipment loads and access platforms.')]
for title,cat,d in projects: Project.objects.update_or_create(slug=title.lower().replace(' ','-').replace('&','and'),defaults={'title':title,'category':cat,'description':d})
print('Seed complete')
